### ISSUE TITLE
factom.exceptions.InternalError: -32603: Internal error

### ISSUE THREAD

**Issue by metalheadani** [FactomProject/factom-api#4]
from factom import Factomd, FactomWalletd

fct_address = 'FA2fddGggXiSqcUSbmDDjNTjpxCerZewoZy5iGTMXGoA4HWiTKW6'
ec_address = 'EC2MWRrooo3t7W5yioH1hZSKcDSjJ8LNRyUwVGi58ZSgk5YJ9KKr'

walletd = FactomWalletd()

factomd = Factomd(
	host='http://172.17.0.1:8088',
	fct_address = fct_address,
	ec_address = ec_address,
	username='userabc',
	password='password'
	)

walletd.new_chain(factomd, ['random', 'chain', 'id'], 'content',ec_address=ec_address)

#This gives an error:

raceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ubuntu/factom_api/lib/python3.6/site-packages/factom/client.py", line 237, in new_chain
    'ecpub': ec_address or self.ec_address
  File "/home/ubuntu/factom_api/lib/python3.6/site-packages/factom/client.py", line 73, in _request
    handle_error_response(resp)
  File "/home/ubuntu/factom_api/lib/python3.6/site-packages/factom/exceptions.py", line 18, in handle_error_response
    raise codes[code](message=message, code=code, data=data, response=resp)
factom.exceptions.InternalError: -32603: Internal error

I can't understand what is the InternalError. What am I doing wrong or is there any problem with any dependency?

**Comment by TRGG3R** [comment]
I tried duplicating your issue. It appears that chain exists with the same ExtIds. Because of this, my understanding is you are unable to add the chain. I'm assuming you are using the testnet. Have you attempted the walletd.new_chain command with other extIDs? Also, are you able to make entries to that chainID: da2ffed0ae7b33acc718089edc0f1d001289857cc27a49b6bc4dd22fac971495 

I can look into adding a way to query if the chain exists prior to submitting the new_chain command to prevent this error. We are also in the process of improving the exceptions.

**Comment by samuelvanderwaal** [comment]
I'm getting this same error with the following code, so, at least in my case, I don't think it's a duplicate chain issue.

```import random
from factom import Factomd, FactomWalletd

factomd = Factomd()
walletd = FactomWalletd()

ec_address = "EC1rNdDzM1DYrwncnm5io7XU5KdSpM2h2wKrjVe5gxV4n4EUnWRf"

rand_num1 = random.randint(0, 1E15)
rand_num2 = random.randint(0, 1E15)
rand_num3 = random.randint(0, 1E15)

response = walletd.new_chain(factomd, [str(rand_num1), str(rand_num2)], str(rand_num3),
                             ec_address=ec_address)

print(response)
```
Error response:

```Traceback (most recent call last):
  File "test.py", line 14, in <module>
    ec_address=ec_address)
  File "/home/samuel/.local/share/virtualenvs/test-p_eD4be_/lib/python3.7/site-packages/factom/client.py", line 509, in new_chain
    "ecpub": ec_address or self.ec_address,
  File "/home/samuel/.local/share/virtualenvs/test-p_eD4be_/lib/python3.7/site-packages/factom/client.py", line 67, in _request
    handle_error_response(resp)
  File "/home/samuel/.local/share/virtualenvs/test-p_eD4be_/lib/python3.7/site-packages/factom/exceptions.py", line 20, in handle_error_response
    raise codes[code](message=message, code=code, data=data, response=resp)
factom.exceptions.InvalidParams: -32602: Invalid params
```

**Comment by sambarnes** [comment]
@samuelvanderwaal this is part of the recent changes in the version bump to 1.0  for the lib. These functions now take encoded parameters (bytes-like or hex strings), rather than passing in a plain string to be encoded. Allows for more flexible usage of extids and content fields.

Your code snippet would be:
```
response = walletd.new_chain(factomd, [str(rand_num1).encode(), str(rand_num2).encode()], str(rand_num3).encode(), ec_address=ec_address)
```

Or you can use `int.to_bytes()` instead if you dont wanna convert to strings

The docstrings are updated but I suppose I forgot to update the examples in the README. Will do that soon

**Comment by samuelvanderwaal** [comment]
Thanks! This works but I don't quite understand why:

`"extids": [utils.hex_from_bytes_or_string(x) for x in ext_ids],`

calls this function:

```
def hex_from_bytes_or_string(x: Union[bytes, str]):
    return x if type(x) is str else x.hex()
```
which just returns the value if it's a string, otherwise it converts the value to hex. Why does this disallow me from passing strings then?

**Comment by sanchopansa** [comment]
It’s `factomd` that’s disallowing you from sending an un-encoded string and then the Python library throws the exception.

The input should be an encoded string (which is still of type `str` same as an un-encoded one), so that’s why it’s a valid invocation.

In principle, we could have a stricter check already on the Python side, but my opinion is that it makes more sense to keep the logic lighter in the library and delegate those validations to `factomd`. I guess we should be much clearer with the examples though.

**Comment by samuelvanderwaal** [comment]
That makes sense; thanks for the response. I think it's fine how it is I just wanted to understand what was going on for my own edification.
